### PR TITLE
WIP: Upgrading to Alpine 3.6 + Adding back the UID/GID capability

### PR DESCRIPTION
**Pull request by dduportal**
Signed-off-by: Damien DUPORTAL <damien.duportal@gmail.com>

Hello there!

I'm using your docker image for Codiad, and I had the need to move to the alpine, AND having to use GUI/UID tuning. 

So please find here a 1st version with a full upgrade to alpine Linux 3.6, released recently, and the commands usermod and groupmod are now installed (package shadow introduced in 3.6 repo).

Work to DO:

* [ ] I've also installed tini: I'm still testing. It is a process reaper that will take care of forwarding/killing anything from entrypoint.sh. Maybe we could remove s6 due to this and launch processes from shell?
* [ ] Updating documentation if you are OK?

### CODE REVIEW

**Comment by wernight** [comment]
Instead of tini, may use [dumb-init](https://github.com/Yelp/dumb-init) which works on Alpine (see my images as some use it).

**Comment by wernight** [comment]
Looks good so far.

**Comment by dduportal** [comment]
Hello !

I propose to manage the init reaper subject on another PR, to go step by step if you agree ?

FYI, tini already exists in APK repository since Alpine 3.4 (ref. https://pkgs.alpinelinux.org/packages?name=tini&branch=&repo=&arch=&maintainer=), but dumb-init is also a good fit (never used it, so happy to try and learn:) ).

I need to update doc then, in order to make this PR mergable.

**Comment by wernight** [comment]
Noting that tini is also a good fit:

> @hakre I believe the dumb-init folks were not aware of Tini when they wrote it, so it's not like they found something fundamentally wrong with Tini that they wanted to fix with dumb-init :). There are a few feature differences between the two. For example they support signal rewriting and Tini doesn't, but Tini supports subreapers and they don't. Overall, though, if you're looking for zombie reaping and that's it, either will do.

**Pull request merged**
